### PR TITLE
Map updates

### PR DESCRIPTION
**Pull request by hermaplusplus**
## About The Pull Request

Fixes the issue with disposals and revamps the maintenance/fire department

## Why It's Good For The Game

The disposals problem was a bit of a problem since it would spit things out into some lots (and contribute to savetimes).

## Changelog
:cl:
fix: Fixes disposals system
tweak: Makes the disposal outlet beneath engineering better
tweak: Separates maintenance department from sanitech area
add: Adds a pretty cool department overall
add: Adds engineering gear
add: Adds firefighting gear
add: Adds water and fuel tanks
add: Adds disposal pipe dispenser
add: Adds MD/PWD/CE office
add: Adds mechanic's garage
fix: Fixes loads more miscellaneous bugs
/:cl:

### CODE REVIEW

**Comment by hermaplusplus** [comment]
Do not merge! This PR is not tested yet, and there are outstanding tweaks to do.

- [ ] Ensure disposal system is actually working properly
- [ ] Ensure door names are correct
- [ ] Secure the CE office
- [ ] Do a full test of the update

**Comment by hermaplusplus** [comment]
If you want to do updates at the same time (looking at you @N8-Toe), make a PR to `hermaplusplus:map-updates` and **use mapmerge2** (and don't commit the `.backup`, `.before`, or `.pyc` files)!

**Comment by N8-Toe** [comment]
I feel called out

**Comment by hermaplusplus** [comment]
- [X] Do a **good enough** test of the update

**Comment by hermaplusplus** [comment]
More to-dos:

- [ ] Implement proper access requirements on doors
- [ ] Double check disposal system

**Comment by hermaplusplus** [comment]
This PR is definitely getting squashed

**Pull request merged**
